### ISSUE TITLE
ubuntu centos下anywhere运行报错

### ISSUE THREAD

**Issue by bi-kai** [JacksonTian/anywhere#18]
anywhere运行报错，centos和Ubuntu都这样（win下是好的）：
anywhere -v

···node
Running at http://10.180.44.232:8000/
Also running at https://10.180.44.232:8001/
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3
···

其他node全局模块是可以运行的。

**Comment by JacksonTian** [comment]
你机器上没有xdg-open。`anywhere -s` 这样启动吧。

**Comment by bi-kai** [comment]
ok，这样是可以起来了。我的是Linux服务器，不带图形界面，是应该带-s，谢谢~
