### ISSUE TITLE
是否应该检测浏览器是否存在

### ISSUE THREAD

**Issue by springjk** [JacksonTian/anywhere#28]
> https://github.com/JacksonTian/anywhere/blob/master/bin/anywhere#L59

在 Linux Server 端，没有 GUI 没有 Browser, 如果不使用 -s 就会默认打开浏览器产生异常，错误如下：

```shell
/workspace anywhere                                                                                 /workspace 130 ↵ 
Running at http://172.17.0.2:8000/
Also running at https://172.17.0.2:8001/
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at exports._errnoException (util.js:1020:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
    at onErrorNT (internal/child_process.js:376:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:606:11)
    at run (bootstrap_node.js:383:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:496:3
```

我的建议，如果要默认打开的话，是否可以增加浏览器检测，或者一些其他手段防止异常，比如 Catch 掉产生 Warning？否则一开始运行的时候很容易搞不清状况，不知道是少了 -s 才能运行。

**Comment by JacksonTian** [comment]
在设计上 就是假设用户已经有了浏览器的。可以考虑更健壮一些。

**Comment by hstarorg** [comment]
@JacksonTian  觉得建议挺好，可以吃掉异常。

**Comment by springjk** [comment]
> 假设用户已经有了浏览器 

这条本身就不太合理，一个命令行工具运行在 no-ui server 还是很常见的，个人认为 try-catch 掉然后给出 Warning 浏览器无法打开 这样会更友好，这样就不会出现运行命令直接出异常以为工具出问题的情况了。
