### ISSUE TITLE
Error: spawn xdg-open ENOENT

### ISSUE THREAD

**Issue by JZLeung** [JacksonTian/anywhere#35]
```bash
ubuntu@VM-0-8-ubuntu:~$ anywhere -h localhost -p 8888
Running at http://localhost:8888/
Also running at https://localhost:8889/
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
npm: 5.6.0
node: v8.11.1
os: ubuntu 16.04

**Comment by JacksonTian** [comment]
该命令不在。

如果你不需要浏览器打开，请增加 -s 参数，如果需要，请安装该命令。
