### ISSUE TITLE
树莓派 - SSL routines:SSL_CTX_use_certificate:ee key too small

### ISSUE THREAD

**Issue by mymmoonoa** [JacksonTian/anywhere#52]
之前树莓派还能用
新装遇到错误
```
root@pi4-001:/home/pi# anywhere -p 8080 -s
_tls_common.js:135
      c.context.setCert(cert);
                ^

Error: error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small
    at Object.createSecureContext (_tls_common.js:135:17)
    at Server (_tls_wrap.js:903:27)
    at new Server (https.js:62:14)
    at Object.createServer (https.js:85:10)
    at Object.<anonymous> (/root/.nvm/versions/node/v10.23.0/lib/node_modules/anywhere/bin/anywhere:131:7)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

```

应该是和 https://github.com/jfromaniello/selfsigned/issues/33 类似，key需要改成2048，还望作者可以更新下

**Comment by JacksonTian** [comment]
可以发一个 PR 吗。

**Comment by O-Connects** [comment]
MacOS也不行

**Comment by hstarorg** [comment]
这个问题是 node 版本升级，依赖的 openssl 对秘钥强度有新的要求，稍后我提一个PR。

**Comment by hstarorg** [comment]
https://github.com/JacksonTian/anywhere/pull/68

**Comment by JacksonTian** [comment]
@hstarorg 感谢 contribute。新版本已经发布。
